default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: werecommend_dev

test:
  <<: *default
  database: werecommend_test

production:
  <<: *default
  database: werecommend

staging:
  <<: *default
  database: <%= Rails.application.credentials.staging[:db][:db] %>
  username: <%= Rails.application.credentials.staging[:db][:user] %>
  password: <%= Rails.application.credentials.staging[:db][:password] %>
