default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: awoolo_dev

test:
  <<: *default
  database: awoolo_test

production:
  <<: *default
  database: awoolo_production

staging:
  <<: *default
  database: awoolo_staging
