default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: autospecsdirect_dev

test:
  <<: *default
  database: autospecsdirect_test

staging:
  <<: *default
  host: localhost
  database: autospecsdirect_staging
  username: autospecsdirect_staging
  password: <%= Rails.application.credentials.production[:staging_db][:password] %>

production:
  <<: *default
  host: localhost
  database: <%= Rails.application.credentials.production[:db][:db] %>
  username: <%= Rails.application.credentials.production[:db][:user] %>
  password: <%= Rails.application.credentials.production[:db][:password] %>
