default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: awoolo_dev

test:
  <<: *default
  database: awoolo_test

production:
  <<: *default
  host: localhost
  database: <%= Rails.application.credentials.production[:db][:db] %>
  username: <%= Rails.application.credentials.production[:db][:user] %>
  password: <%= Rails.application.credentials.production[:db][:password] %>

staging:
  <<: *default
  host: localhost
  database: <%= Rails.application.credentials.staging[:db][:db] %>
  username: <%= Rails.application.credentials.staging[:db][:user] %>
  password: <%= Rails.application.credentials.staging[:db][:password] %>
